baseURL = "https://www.freethinker.top"
languageCode = "zh"
DefaultContentLanguage = "zh"
theme = "diary"

title = "御秋博客"
enableInlineShortcodes = true
enableEmoji = true
googleAnalytics = ""

[params]
  lazyImage = false
  enableMathJax = false # enable it in Front Matter
  enableReadingTime = true
  favicon = "favicon.ico"
  startyear = "2019"
  description = "xxxxx"
  disqus = ""
  #toc = true
  walineServer = 'https://waline-beta-plum.vercel.app/'

#[params.waline]
#  enable = true
#  lang = 'zh-CN' # zh-CN
#  appId = 'IyRdCooou4lRgtrqYYEIDgRK-gzGzoHsz'
#  appKey = '3hXIq4IuQBcg76WWjetWOrMO'
#  placeholder = ''
#  requiredFields = ['nick', 'mail']
#  avatar = 'robohash'
#  visitor = true
#  serverURLS = 'https://api.freethinker.top'
#  walineServer = 'https://api.freethinker.top'
#  debug = true # display the visitor counts when using 'hugo server'

[menu]
  [[menu.main]]
  name = "主页 Home"
  url = "/"
  weight = 1
  [[menu.main]]
  name = "标签 Tags"
  url = "/tags/"
  weight = 2
  [[menu.main]]
  name = "分类 Categories"
  url = "/categories/"
  weight = 3

[social]
  # github = "https://github.com/kkk8s"
  rss = "index.xml"

[taxonomies]
category = "categories"
tag = "tags"

# doc: https://gohugo.io/getting-started/configuration-markup#highlight
# syntax style: https://xyproto.github.io/splash/docs/longer/all.html
[markup]
  [markup.highlight]
    guessSyntax = true
    hl_Lines = ""
    # lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "dracula" # github, dracula, vim, monokai
    tabWidth = 4
   
  [markup.tableOfContents]
    endLevel = 5
    startLevel = 1
